/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ctyun_ec_jni_Galois */

#ifndef _Included_cn_ctyun_ec_jni_Galois
#define _Included_cn_ctyun_ec_jni_Galois
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_single_multiply
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1single_1multiply
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_single_divide
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1single_1divide
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_log
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1log
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_ilog
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1ilog
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_create_log_tables
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1create_1log_1tables
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_logtable_multiply
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1logtable_1multiply
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_logtable_divide
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1logtable_1divide
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_create_mult_tables
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1create_1mult_1tables
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_multtable_multiply
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1multtable_1multiply
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_multtable_divide
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1multtable_1divide
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_shift_multiply
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1shift_1multiply
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_shift_divide
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1shift_1divide
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_create_split_w8_tables
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1create_1split_1w8_1tables
  (JNIEnv *, jclass);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_split_w8_multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1split_1w8_1multiply
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_inverse
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1inverse
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_shift_inverse
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1shift_1inverse
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_region_xor
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1region_1xor
  (JNIEnv *, jclass, jobject, jobject, jobject, jint);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_w08_region_multiply
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1w08_1region_1multiply
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jboolean);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_w16_region_multiply
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1w16_1region_1multiply
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jboolean);

/*
 * Class:     cn_ctyun_ec_jni_Galois
 * Method:    galois_w32_region_multiply
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_cn_ctyun_ec_jni_Galois_galois_1w32_1region_1multiply
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
