/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ctyun_ec_jni_Liberation */

#ifndef _Included_cn_ctyun_ec_jni_Liberation
#define _Included_cn_ctyun_ec_jni_Liberation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ctyun_ec_jni_Liberation
 * Method:    liberation_coding_bitmatrix
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_ctyun_ec_jni_Liberation_liberation_1coding_1bitmatrix
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Liberation
 * Method:    liber8tion_coding_bitmatrix
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_ctyun_ec_jni_Liberation_liber8tion_1coding_1bitmatrix
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_ctyun_ec_jni_Liberation
 * Method:    blaum_roth_coding_bitmatrix
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_ctyun_ec_jni_Liberation_blaum_1roth_1coding_1bitmatrix
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Liberation
 * Method:    my_liberation_coding_bitmatrix
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_cn_ctyun_ec_jni_Liberation_my_1liberation_1coding_1bitmatrix
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_ctyun_ec_jni_Liberation
 * Method:    my_liber8tion_coding_bitmatrix
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_cn_ctyun_ec_jni_Liberation_my_1liber8tion_1coding_1bitmatrix
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_ctyun_ec_jni_Liberation
 * Method:    my_blaum_roth_coding_bitmatrix
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_cn_ctyun_ec_jni_Liberation_my_1blaum_1roth_1coding_1bitmatrix
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
